- name: app_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yml

- name: python_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python-setup.yml

- name: systemd_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yml

- name: restart payment
  ansible.builtin.service:
    name: payment
    state: restarted
    enabled: yes
