- name: Install MySQL server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Start and enable MySQL server
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes  

- name: Setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass "{{ MY_SQL_ROOT_PASSWORD }}"